export const Products = {
    cancelled: [
        {
            date: '18/08/20',
            product: 'macbook pro',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'cancelled',
            paymentType: 'debit card',
            id: 20695,
            amount: {
                cost: '$350.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'xbox',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'cancelled',
            paymentType: 'debit card',
            id: 20334,
            amount: {
                cost: '$150.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'cancelled',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
    ],

    completed: [
        {
            date: '18/08/20',
            product: 'macbook pro',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20695,
            amount: {
                cost: '$350.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'xbox',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20334,
            amount: {
                cost: '$150.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'completed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
    ],

    pending: [
        {
            date: '18/08/20',
            product: 'macbook pro',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'pending',
            paymentType: 'debit card',
            id: 20695,
            amount: {
                cost: '$350.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'xbox',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'pending',
            paymentType: 'debit card',
            id: 20334,
            amount: {
                cost: '$150.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'pending',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
    ],

    onhold: [
        {
            date: '18/08/20',
            product: 'macbook pro',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'onhold',
            paymentType: 'debit card',
            id: 20695,
            amount: {
                cost: '$350.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'xbox',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'onhold',
            paymentType: 'debit card',
            id: 20334,
            amount: {
                cost: '$150.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'onhold',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
    ],
    refunded: [
        {
            date: '18/08/20',
            product: 'macbook pro',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'refunded',
            paymentType: 'debit card',
            id: 20695,
            amount: {
                cost: '$350.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'xbox',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'refunded',
            paymentType: 'debit card',
            id: 20334,
            amount: {
                cost: '$150.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'refunded',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
    ],

    failed: [
        {
            date: '18/08/20',
            product: 'macbook pro',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'failed',
            paymentType: 'debit card',
            id: 20695,
            amount: {
                cost: '$350.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'xbox',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'failed',
            paymentType: 'debit card',
            id: 20334,
            amount: {
                cost: '$150.00',
                currency: 'dollar',
            },
        },
        {
            date: '18/08/20',
            product: 'iPad air',
            quantity: 2,
            tracking: '3wc32Gvf',
            status: 'failed',
            paymentType: 'debit card',
            id: 20565,
            amount: {
                cost: '#350.00',
                currency: 'naira',
            },
        },
    ],
};
