const fakeData = [
    {
        id: 1,
        product_name: 'Shirts',
        description: 'For all formal occasions',
        remainder: '3 left',
        cart: '/img/cart.png',
        stars: '/img/stars.png',
        price: 25,
        currency: 'N',
        slashPrices: 30,
        thumb: '/img/dryer.png',
        alt: 'shirts',
    },
    {
        id: 2,
        product_name: 'Trousers',
        description: 'Fits perfectly',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 30,
        currency: 'N',
        slashPrices: 50,
        thumb: '/img/google-home.png',
        alt: 'trousers',
    },
    {
        id: 3,
        product_name: 'Glasses',
        description: 'Lenses for all',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 10,
        currency: 'N',
        slashPrices: 30,
        thumb: '/img/dryer.png',
        alt: 'glasses',
    },
    {
        id: 4,
        product_name: 'Grocery',
        description: 'Foods, Beverages, Home-bl tools',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 20,
        currency: 'N',
        slashPrices: 50,
        thumb: '/img/google-home.png',
        alt: 'grocery',
    },
    {
        id: 5,
        product_name: 'Shoes',
        description: 'Comfy as can be',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 15,
        currency: 'N',
        slashPrices: 30,
        thumb: '/img/toaster.png',
        alt: 'shoes',
    },
    {
        id: 6,
        product_name: 'Bags',
        description: 'Carry all',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 25,
        currency: 'N',
        slashPrices: 50,
        thumb: '/img/microwave.png',
        alt: 'bags',
    },
    {
        id: 7,
        product_name: 'Shirts',
        description: 'For all formal occasions',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 25,
        currency: 'N',
        slashPrices: 30,
        thumb: '/img/toaster.png',
        alt: 'shirts',
    },
    {
        id: 8,
        product_name: 'Trousers',
        description: 'Fits perfectly',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 30,
        currency: 'N',
        slashPrices: 50,
        thumb: '/img/microwave.png',
        alt: 'trousers',
    },
    {
        id: 9,
        product_name: 'Glasses',
        description: 'Lenses for all',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 10,
        currency: 'N',
        slashPrices: 30,
        thumb: '/img/headsets.png',
        alt: 'glasses',
    },
    {
        id: 10,
        product_name: 'Grocery',
        description: 'Foods, Beverages, Home-bl tools',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 200,
        currency: 'N',
        slashPrices: 500,
        thumb: '/img/vr.png',
        alt: 'grocery',
    },
    {
        id: 11,
        product_name: 'Shoes',
        description: 'Comfy as can be',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 15,
        currency: 'N',
        slashPrices: 30,
        thumb: '/img/headsets.png',
        alt: 'shoes',
    },
    {
        id: 12,
        product_name: 'Bags',
        description: 'Carry all',
        remainder: '3 left',
        stars: '/img/stars.png',
        cart: '/img/cart.png',
        price: 25,
        currency: 'N',
        slashPrices: 50,
        thumb: '/img/vr.png',
        alt: 'bags',
    },
];

export default fakeData;
