export const FakeQAOrders = [
    {
        _id: '95405',
        placedOn: '18/08/20',
        product: 'Macbook Pro',
        quantity: 2,
        status: 'Completed',
        paymentType: 'Debit Card',
        totalCost: 45000,
        trackingID: '3cw32Gvf',
    },
    {
        _id: '952034',
        placedOn: '18/08/20',
        product: 'xbox',
        quantity: 2,
        trackingID: '3wc32Gvf',
        status: 'Cancelled',
        paymentType: 'debit card',
        totalCost: 50000,
    },
    {
        placedOn: '18/08/20',
        product: 'iPad air',
        quantity: 1,
        trackingID: '3wc32Gvf',
        status: 'Onhold',
        paymentType: 'debit card',
        _id: '20565',
        totalCost: 35000,
    },
    {
        placedOn: '18/08/20',
        product: 'Macbook Air',
        quantity: 2,
        trackingID: '3wc32Gvf',
        status: 'Pending',
        paymentType: 'debit card',
        _id: '20695',
        totalCost: 560000,
    },
    {
        placedOn: '18/08/20',
        product: 'xbox',
        quantity: 2,
        trackingID: '3wc32Gvf',
        status: 'Refunded',
        paymentType: 'debit card',
        _id: '20334',
        totalCost: 40000,
    },
    {
        placedOn: '18/08/20',
        product: 'iPad Globe',
        quantity: 2,
        trackingID: '3wc32dvf',
        status: 'Refunded',
        paymentType: 'debit card',
        _id: '20540',
        totalCost: 90000,
    },
    {
        placedOn: '18/08/20',
        product: 'Samsung S20',
        quantity: 2,
        trackingID: '3wc32dvf',
        status: 'Failed',
        paymentType: 'Flutter Wave',
        _id: '40540',
        totalCost: 519000,
    },
];

export const ActionList = [
    {
        id: '1',
        name: 'Delivered',
    },
    {
        id: '2',
        name: 'Returned',
    },
    {
        id: '3',
        name: 'Completed',
    },
    {
        id: '4',
        name: 'Cancelled',
    },
    {
        id: '5',
        name: 'Onhold',
    },
    {
        id: '6',
        name: 'Failed',
    },
    {
        id: '7',
        name: 'Refunded',
    },
];
