name: PR Workflow

on:
  pull_request:
    branches:
      # PR events on master branch
      - master
      # PR events on develop branch
      - develop
  push:
    branches:
      # Push events on develop branch
      - develop

jobs:
  lint:
    name: Linting Audit
    runs-on: ubuntu-latest
    # set Node.js versions
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Use a Node.js version from list
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # cache node modules for faster test
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # installs  Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # Run linting audits
      - name: Run Lint Audits
        run: yarn lint
        # set environment variables
        env:
          CI: true
  test:
    name: Automated Tests
    runs-on: ubuntu-latest
    # Waits for lint job for each Node.js version to complete
    needs: lint
    # set Node.js versions
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Use a Node.js version from list
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # cache node modules for faster test
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        # installs  Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

        # Run automated tests
      - name: Run tests
        run: yarn test:ci

        # set environment variables
        env:
          CI: true
  lighthouse:
    name: Light House Audit
    runs-on: ubuntu-latest
    # Waits for lint and test jobs for each Node.js version to complete
    needs: [ lint, test ]
    # set Node.js versions
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Use a Node.js version from list
      - name: Use Node.js  ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # cache node modules for faster audit
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # cache nextjs builds for faster builds
      - name: Cache nextjs builds
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      # installs  Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # installs  Dependencies
      - name: Build
        run: yarn build

      # Run Lighthouse Audit
      - name: Install Lighthouse
        run: npm install -g @lhci/cli@0.4.x

      # Run Lighthouse Audit
      - name: Run Lighthouse Audit
        run: lhci autorun
